<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>harness</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <NoWarn>CS8981</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTK" Version="3.3.3" />
    <PackageReference Include="OpenTK.GLControl" Version="3.3.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Harness.cs" />
    <Compile Include="Stubs2.cs" />
    <Compile Include="..\osucatch-editor-realtimeviewer\QuickToggleDocking.cs" Link="QuickToggleDocking.cs" />
    <Compile Include="..\osucatch-editor-realtimeviewer\BarLineSettings.cs" Link="BarLineSettings.cs" />
    <Compile Include="..\osucatch-editor-realtimeviewer\QuickToggleBar.cs" Link="QuickToggleBar.cs" />
  </ItemGroup>
</Project>

