name: Release

on:
  push:
    branches:
      - "master"
      
jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore osucatch-editor-realtimeviewer
      
    - name: Build x64
      run: dotnet build osucatch-editor-realtimeviewer -c Release /p:Platform=x64 --no-restore

    - name: Create x64 release.zip
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'release.zip'
        directory: 'osucatch-editor-realtimeviewer/bin/x64/Release/net8.0-windows7.0/win-x64/'

    - name: Generate release tag
      id: generate_release_tag
      uses: alexvingg/next-release-tag@v1.0.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''

    - name: Create Release
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: ${{ steps.generate_release_tag.outputs.release_tag }}
        title: Release ${{ steps.generate_release_tag.outputs.release_tag }}
        files: |
          osucatch-editor-realtimeviewer/bin/x64/Release/net8.0-windows7.0/win-x64/release.zip